# Counting Values

> Counting unique elements in a sequence in various ways (absolute and cumulative, count and percentage).

In [ ]:
#| default_exp value_counts_plus

In [ ]:
#| hide
from nbdev.showdoc import *

In [ ]:
#| export
import pandas as pd

In [ ]:
#| export
def value_counts_plus(
    series,
    dropna=False,
    show_top=10,
    sort_others=False,
    style=True,
    background_gradient='cividis'):
    """
    Provide a few ways of showing counts of values of items in ``series``.
    
    Parameters
    ----------
    series : pandas Series or list
        A sequence of items to count.
    dropna : bool
        Whether or not to drop missing values.
    show_top : int
        How many of the top rows to display.
    sort_others : bool
        Whether or not to place "Others" in the bottom (default) or in its sorted order position
    style : bool
        Whether or not to style values for easier reading. If set to ``True`` the result would
        not be a DataFrame, and cannot be further manipulated. Set the value to ``False`` to
        get aDataFrame as the return value.

    Returns
    -------
    value_counts_df : a pandas.DataFrame showing counts based on the provided arguments        
    """
    series = pd.Series(series)
    series.name = series.name or 'data'
    col = series.name or 'data'
    val_counts = series.value_counts(dropna=dropna)
    if len(val_counts) > show_top:
        val_counts = pd.concat([
            val_counts[:show_top],
            pd.Series(val_counts[show_top:].sum(), index=['Others:'], name=col)])
        if sort_others:                                                
            val_counts = val_counts.sort_values(ascending=False)                                                
        show_top += 1
    count_df = (val_counts
                .to_frame()
                .assign(cum_count=lambda df: df[col].cumsum(),
                        perc=lambda df: df[col].div(df[col].sum()),
                        cum_perc=lambda df: df['perc'].cumsum())
                .reset_index()
                .rename(columns={'index': col, col: 'count'}))
    if not style:
        return count_df.head(show_top)
    return (count_df.
            head(show_top).style
            .format({'count': '{:,}', 'cumsum': '{:,}', 
                     'perc': '{:.1%}',
                     'cum_count': '{:,}',
                     'cum_perc': '{:.1%}'})
            .background_gradient(background_gradient)
            .highlight_null()
            .set_caption(f'<h2>Counts of <b>{series.name}</b></h2>'))

### Counting a list of status codes - default

In [ ]:
import random
from http import HTTPStatus

import pandas as pd

status_codes = random.choices(
    [s.value for s in HTTPStatus],
    weights=[.01, 0.04, 0.1] * 20 + [0.1, 0.3],
    k=10000)
value_counts_plus(status_codes)

### Changing the number of displayed rows with `show_top`

In [ ]:
value_counts_plus(status_codes, show_top=15)

### Sorting "Others:"

In [ ]:
value_counts_plus(status_codes, sort_others=True)

### Removing table styling if you want a pure `DataFrame`:

In [ ]:
value_counts_plus(status_codes, style=False)

       data  count  cum_count    perc  cum_perc
0       511    903        903  0.0903    0.0903
1       407    315       1218  0.0315    0.1218
2       416    313       1531  0.0313    0.1531
3       201    309       1840  0.0309    0.1840
4       424    309       2149  0.0309    0.2149
5       421    303       2452  0.0303    0.2452
6       102    296       2748  0.0296    0.2748
7       428    295       3043  0.0295    0.3043
8       508    294       3337  0.0294    0.3337
9       303    293       3630  0.0293    0.3630
10  Others:   6370      10000  0.6370    1.0000

### Changing the colormap used with `background_gradient`

In [ ]:
value_counts_plus(status_codes, background_gradient='Greens')

### Convert the table to raw HTML for embedding in a blog or web page

In [ ]:
print(value_counts_plus(status_codes).to_html()[:700])

<style type="text/css">
#T_c20ac_row0_col1, #T_c20ac_row0_col3 {
  background-color: #083370;
  color: #f1f1f1;
}
#T_c20ac_row0_col2, #T_c20ac_row0_col4, #T_c20ac_row1_col1, #T_c20ac_row1_col3, #T_c20ac_row2_col1, #T_c20ac_row2_col3, #T_c20ac_row3_col1, #T_c20ac_row3_col3, #T_c20ac_row4_col1, #T_c20ac_row4_col3, #T_c20ac_row5_col1, #T_c20ac_row5_col3, #T_c20ac_row6_col1, #T_c20ac_row6_col3, #T_c20ac_row7_col1, #T_c20ac_row7_col3, #T_c20ac_row8_col1, #T_c20ac_row8_col3, #T_c20ac_row9_col1, #T_c20ac_row9_col3 {
  background-color: #00224e;
  color: #f1f1f1;
}
#T_c20ac_row1_col2, #T_c20ac_row1_col4 {
  background-color: #00285b;
  color: #f1f1f1;
}
#T_c20ac_row2_col2, #T_c20ac_row2_col4 {
  bac

In [ ]:
#| hide
import nbdev; nbdev.nbdev_export()