---
format:
  revealjs:
    slide-number: true
    scrollable: true
    touch: true
    controls: true
---

<h1>Counting values with <code>adviz</code></h1>

## Counting values

> Count the unique values in a collection of items

* Count in absolute and proportion (percentage) terms
* Show the cumulative count and percent
* Determine the number of top items to show
* Show all remaining items lumped into one item named `Others:`
* Change the name of the items, as well as the caption and various other styling options

## Installation and usage

#### Installation:

```bash
python3 -m pip install adviz
```

#### Usage:

```python
import adviz
adv.value_counts_plus([item_1, item_2, ... item_n], ...)

```

## Usage

Generate a random list of 10,000 colors

In [ ]:
#| echo: true
#| code-fold: true
import random
import numpy as np
import matplotlib as mpl

colors = list(mpl.colors.cnames.keys())
colors = random.choices(colors, weights=[0.9, 0.04, 0.05, 0.09]*37, k=10_000)
colors += [np.nan for i in range(240)]
colors[:20]

['mediumaquamarine',
 'linen',
 'mediumslateblue',
 'papayawhip',
 'palegoldenrod',
 'lightgreen',
 'rebeccapurple',
 'lightgreen',
 'darkred',
 'blanchedalmond',
 'cyan',
 'mediumslateblue',
 'mediumseagreen',
 'darkslategray',
 'dodgerblue',
 'linen',
 'lightsteelblue',
 'dodgerblue',
 'red',
 'lightcoral']

In [ ]:
from functools import partial
import adviz
adviz.value_counts_plus = partial(adviz.value_counts_plus, size=14)

## View default output

In [ ]:
#| echo: true
import adviz
adviz.value_counts_plus(colors)

## Change the number of top values: `show_top=n`

In [ ]:
#| echo: true
adviz.value_counts_plus(colors, show_top=5)

## Remove styling: `style=False`

In [ ]:
#| echo: true
#| body-width: 200px
adviz.value_counts_plus(colors, show_top=5, style=False)

            data  count  cum_count      perc  cum_perc
0         sienna    265        265  0.025879  0.025879
1          linen    251        516  0.024512  0.050391
2       darkgray    246        762  0.024023  0.074414
3  darkslategray    244       1006  0.023828  0.098242
4            NaN    240       1246  0.023438  0.121680
5        Others:   8994      10240  0.878320  1.000000

## Styled vs non-styled tables
* Indexing starts with 1 to be more accessible to non-tech audience
* Indexing remains 0-based in non-styled tables for further processing
* Column headers are displayed in a more readable way

In [ ]:
#| layout-ncol: 2
display(adviz.value_counts_plus(colors, show_top=5))
display(adviz.value_counts_plus(colors, show_top=5, style=False))

            data  count  cum_count      perc  cum_perc
0         sienna    265        265  0.025879  0.025879
1          linen    251        516  0.024512  0.050391
2       darkgray    246        762  0.024023  0.074414
3  darkslategray    244       1006  0.023828  0.098242
4            NaN    240       1246  0.023438  0.121680
5        Others:   8994      10240  0.878320  1.000000

## Change the size of the table: `size`

In [ ]:
#| echo: true
adviz.value_counts_plus(colors, size=5)

## Change the size of the table: `size`

In [ ]:
#| echo: true
adviz.value_counts_plus(colors, size=20)

## Sort `Others:`
* Are other values significant?
* What would the data look like if all others were in their sorted order?

In [ ]:
#| echo: true
#| incremental: false
adviz.value_counts_plus(colors, sort_others=True)

## Change the theme of the table

In [ ]:
#| echo: true
adviz.value_counts_plus(colors, background_gradient='magma')

## Get the reverse of the theme by adding `_r`

In [ ]:
#| echo: true
adviz.value_counts_plus(colors, background_gradient='magma_r')

## Remove missing values: `dropna`

In [ ]:
#| echo: true
adviz.value_counts_plus(colors, dropna=True)

## Use different symbols for `thousands` and `decimal`

In [ ]:
#| echo: true
#| column: margin
adviz.value_counts_plus(colors, thousands='.', decimal=',', background_gradient='summer')

## Rename the data column

In [ ]:
#| echo: true
adviz.value_counts_plus(colors, name='colors', background_gradient='cool_r')

## Convert to raw HTML `to_html`

In [ ]:
#| echo: true

html_table = adviz.value_counts_plus(
    colors,
    background_gradient='winter_r',
    thousands='.',
    decimal=',',
    name='Colors').to_html()

print(html_table[:600])

<style type="text/css">
#T_aad9b_row0_col1, #T_aad9b_row0_col3 {
  background-color: #00fe80;
  color: #000000;
}
#T_aad9b_row0_col2, #T_aad9b_row0_col4, #T_aad9b_row1_col1, #T_aad9b_row1_col3, #T_aad9b_row2_col1, #T_aad9b_row2_col3, #T_aad9b_row3_col1, #T_aad9b_row3_col3, #T_aad9b_row4_col1, #T_aad9b_row4_col3, #T_aad9b_row5_col1, #T_aad9b_row5_col3, #T_aad9b_row6_col1, #T_aad9b_row6_col3, #T_aad9b_row7_col1, #T_aad9b_row7_col3, #T_aad9b_row8_col1, #T_aad9b_row8_col3, #T_aad9b_row9_col1, #T_aad9b_row9_col3 {
  background-color: #00ff80;
  color: #000000;
}
#T_aad9b_row1_col2, #T_aad9b_row1_co

## Get started now:
<br><br><br><br>
<h3><code>python3 -m pip install adviz</code></h3><br>

Explore more advertools [data visualizations](https://eliasdabbas.github.io/adviz)